joy_node:
  ros__parameters:
    dev: '/dev/input/js0'
    deadzone: 0.05
    autorepeat_rate: 20.0

joy_driver_node:
  ros__parameters:
    axis_linear_x: 1
    axis_linear_y: 0
    axis_trigger_l2: 7
    axis_trigger_r2: 8
    deadzone_linear: 0.05
    deadzone_angular: 0.05
    max_linear_x: 1.0
    max_linear_y: 1.0
    max_angular_z: 1.5
